<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simple_blog"
 *
 * Auto generated by Extension Builder 2016-04-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Simple Blog',
	'description' => 'My first TYPO3 extension created af TYPO3camp Venlo',
	'category' => 'plugin',
	'author' => 'Ruud Silvrants',
	'author_email' => 't3ext@beech.it',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);